### ISSUE TITLE
Assertion failure when searching LUT-based circuit with MPI

### ISSUE THREAD

**Issue by Pitifulparadox** [dansarie/sboxgates#13]
Hi Marcus! Thank you for your great job on this project. In some cases, when constructing LUT circuits using MPI with the value of -np parameter > 1 I am getting this error.

`$ mpirun -np 10 ./sboxgates -l -b ./sboxes/generated.txt`
`Generating circuits with 1 output. (1/1)`
`Generating circuit for output 0...`
`[   0] Search 5.`
`[   0] Search 7.`
`sboxgates: /mnt/c/Users/HomePC/Desktop/test/sboxgates/lut.c:652: get_nth_combination: Assertion 'n < n_choose_k(num_gates, t)' failed.`
`sboxgates: /mnt/c/Users/HomePC/Desktop/test/sboxgates/lut.c:652: get_nth_combination: Assertion 'n < n_choose_k(num_gates, t)' failed.`
`sboxgates: /mnt/c/Users/HomePC/Desktop/test/sboxgates/lut.c:652: get_nth_combination: Assertion 'n < n_choose_k(num_gates, t)' failed.`
`sboxgates: /mnt/c/Users/HomePC/Desktop/test/sboxgates/lut.c:652: get_nth_combination: Assertion 'n < n_choose_k(num_gates, t)' failed.`
`sboxgates: /mnt/c/Users/HomePC/Desktop/test/sboxgates/lut.c:652: get_nth_combination: Assertion 'n < n_choose_k(num_gates, t)' failed.`
`sboxgates: /mnt/c/Users/HomePC/Desktop/test/sboxgates/lut.c:652: get_nth_combination: Assertion 'n < n_choose_k(num_gates, t)' failed.`
`sboxgates: /mnt/c/Users/HomePC/Desktop/test/sboxgates/lut.c:652: get_nth_combination: Assertion 'n < n_choose_k(num_gates, t)' failed.`
`sboxgates: /mnt/c/Users/HomePC/Desktop/test/sboxgates/lut.c:652: get_nth_combination: Assertion 'n < n_choose_k(num_gates, t)' failed.`
`===================================================================================`
`=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES`
`=   PID 147 RUNNING AT DESKTOP-04EBV37`
`=   EXIT CODE: 6`
`=   CLEANING UP REMAINING PROCESSES`
`=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES`
`===================================================================================`
`YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)`
`This typically refers to a problem with your application.`
`Please see the FAQ page for debugging suggestions`

By changing condition to 'n <= n_choose_k(num_gates, t)' I was able to complete the search. 

I would also like to take this opportunity to ask if your immediate plans include adding the ability to build LUT circuits for sboxes with the number of inputs > 8. It would be an incredible improvement, which I really look forward to.

**Comment by dansarie** [comment]
First of all, sorry for attending to this a bit late. This is indeed an actual bug, before the assertion in question. I'll try to get around to fixing it shortly.

I'm sorry to say I have no immediate plans for supporting 10 bits. That said, it probably wouldn't be too hard to implement, although would likely come with a performance penalty on many platforms. I'll definitely look into it.

**Comment by dansarie** [comment]
Fixed - off-by-one error in an if statement.

Moved the request for S-boxes with more than eight input bits to issue #14.
