### ISSUE TITLE
TRUE undeclared

### ISSUE THREAD

**Issue by richs27** [dansarie/sboxgates#15]
Hi,
I'm very interested in exploring this tool, but unfortunately due to what are still fairly limited development skills on my part, I have struck a build error I hoped you could help with. After running "make", I receive the following:

/home/rs/sboxgates/state.c: In function âload_stateâ:
/home/rs/sboxgates/state.c:242:34: error: âTRUEâ undeclared (first use in this function)
       LOAD_STATE_RETURN_ON_ERROR(TRUE, doc);
                                  ^~~~
/home/rs/sboxgates/state.c:193:7: note: in definition of macro âLOAD_STATE_RETURN_ON_ERRORâ
   if (X) {\
       ^
/home/rs/sboxgates/state.c:242:34: note: each undeclared identifier is reported only once for each function it appears in
       LOAD_STATE_RETURN_ON_ERROR(TRUE, doc);
                                  ^~~~
/home/rs/sboxgates/state.c:193:7: note: in definition of macro âLOAD_STATE_RETURN_ON_ERRORâ
   if (X) {\
       ^
/home/rs/sboxgates/state.c: In function âsave_stateâ:
/home/rs/sboxgates/state.c:106:6: note: The ABI for passing parameters with 32-byte alignment has changed in GCC 4.6
 void save_state(state st) {
      ^~~~~~~~~~
/home/rs/sboxgates/state.c: In function âload_stateâ:
/home/rs/sboxgates/state.c:281:13: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]
       table = generate_ttable_2(type, st.gates[inputs[0]].table, st.gates[inputs[1]].table);
       ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/sboxgates.dir/build.make:134: CMakeFiles/sboxgates.dir/state.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/sboxgates.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

I'm on RHEL 8 and believe I have all the dependencies met although I have had to adjust a couple of paths. Would appreciate a pointer to something I've missed.

Kind regards

**Comment by richs27** [comment]
I've sorted this out now.

**Comment by dansarie** [comment]
Sorry for not responding earlier, but I'm glad you sorted it out by yourself! Is there anything that can be done with the documentation that could be helpful for others running into the same problem?

**Comment by lanpesk** [comment]
I have the same issue, how to solve this problem?
@richs27 , can you give me a advise？
