### ISSUE TITLE
SBOXDiscovery

### ISSUE THREAD

**Issue by acad2** [dansarie/sboxgates#3]
Hi, The page you linked [https://github.com/DeepLearningJohnDoe/SBOXDiscovery] does not exist anymore. Just in case you remember what this project (tried to) do, would you mind a short description in the ReadMe?

**Comment by vdasu** [comment]
@acad2 Looks like repository has been moved [here](https://github.com/tripcode/SBOXDiscovery).

**Comment by dansarie** [comment]
Thanks! Fixed in 3fd731ba3a132e62b3772e4cd3e818bf1027a911
